FormidableLabs/redux-little-router

src/link.js
src/middleware.js

Links weren't generating correct `href`s when using a basename. The basename also got omitted from the pathname in the state tree. Link now accepts a `history` prop to allow use of `history.createHref`.

Fix basename support in middlware and link hrefs

---

package.json
src/create-matcher.js
src/index.js
src/reducer.js
src/store-enhancer.js
test/spec/reducer.spec.jsx
test/spec/store-enhancer.spec.jsx

Change router state payload to include previous and current url info; replace feather-route-matcher with url-pattern and a small wrapper.
This is a breaking change.

Add previous URL info to router state

---

package.json
src/create-matcher.js
test/spec/create-matcher.spec.jsx

Also adds tests for `createMatcher` where the failure occurred.

Replace native find with lodash find for older browsers

---

src/create-matcher.js

This causes a 500 error on SSR when URLs like `xxx/ordering/` fail to match.

Prevent crash on bad route

---

src/index.js
src/link.js
src/middleware.js
src/reducer.js
test/spec/link.spec.jsx
test/spec/middleware.spec.jsx
test/spec/mocks/history.js
test/spec/reducer.spec.jsx

- Expose almost all of the API as public. This allows consumers to hook into the history cycle using the newly exported action types (LOCATION_CHANGED, REPLACE, etc).
- Handle `history`'s `state` field for location-specific state.
- The action creators now take the same arguments as their equivalent `history` functions (either a pathname string or a full location descriptor object).
- `<Link>` now has an optional `replaceState` prop. When true, `<Link>` will dispatch a replace action instead of a push.
- Removed the unused `historyAction` field. This is a breaking change.

Changes for v3

---

src/create-matcher.js

@tptee this allows routes to match when query params are included in the url string.

Don't break on query string.

---

src/index.js
src/middleware.js
src/reducer.js
src/store-enhancer.js
test/spec/middleware.spec.jsx
test/spec/reducer.spec.jsx
test/spec/store-enhancer.spec.jsx

- If there is initial state for the router, dispatch a LOCATION_CHANGED event so that anything dependent on the URL can guarantee to be in sync with the router.
- `createMatcher` now applies directly to actions within the middleware instead of within the reducer. This gives LOCATION_CHANGED richer details and allows consumers to plan for location-dependent side effects without requiring introspection of the state tree.

Initial location action plus more useful LOCATION_CHANGED actions

---

src/store-enhancer.js

This makes the initial location dispatch optional (more flexible/composable for the caller and SSR)

Remove initial dispatch

---

src/index.js

This got removed from the exports at some point, but needs to be there now since we require the user to dispatch the initial location action in v6.

Expose initializeCurrentLocation again

---

src/fragment.js
src/link.js
src/reducer.js
src/store-enhancer.js
test/spec/reducer.spec.jsx

`history.createHref()` adds duplicate basenames to the `href` (https://github.com/ReactTraining/history/issues/169). This solves that.
When matching routes, we matched against `url` instead of `pathname`, which ended up forcing you to hard-code basenames in your routes. This fixes that too!

Fix duplicate basenames in hrefs; avoid matching against full URL

---

package.json
src/create-matcher.js
src/index.js
src/initial-router-state.js
src/link.js
src/store-enhancer.js

Apparently array spread requires the `Symbol` polyfill:
https://babeljs.io/docs/usage/caveats/
We don't want that!

Remove all lodash methods and remove array spread

---

src/store-enhancer.js

Setting basename to '/' prevents routes with a leading '/' from matching. For example, `<Fragment forRoute="/test" />` will throw an exception when the user navigates to `hostname/test`.

Change default basename from '/' to empty string

---

README.md
src/index.js
src/provider.js
test/provider.spec.js

There's interest in using a regular component as an alternative to the higher-ordered component `provideRouter`  in #19. This PR adds that component.
Before:
```js
const componentWithRouter = provideRouter({ store })(YourComponent);
```
After:
```js
// Either the HoC:
const componentWithRouter = provideRouter({ store })(YourComponent);
// Or the plain component:
const elementWithRouter = (
<RouterProvider store={store}>
<YourComponent />
</RouterProvider>
);
```

Allow usage of either an HoC or a component for providing router context

---

src/link.js
test/link.spec.js

Not sure why I didn't do this before, but now all DOM props (including ARIA attributes) work on `<Link>`, not just `className` and `style`.
/cc @divmain @baer

Allow DOM props to pass through Link to the actual a tag

---

.npmignore
.travis.yml
package.json

Getting some strange results on `postinstall` after adding Flow annotations:
```
src/action-types.js -> lib/action-types.js
src/create-matcher.js -> lib/create-matcher.js
src/fragment.js -> lib/fragment.js
src/index.js -> lib/index.js
src/initial-router-state.js -> lib/initial-router-state.js
src/link.js -> lib/link.js
SyntaxError: src/provider.js: Missing class properties transform.
12 | 
 13 | export class RouterProvider extends Component {
> 14 |   router: { store: Store };
    |   ^
 15 | 
 16 |   constructor(props: Props) {
 17 |     super(props);
```
A full `rm -rf node_modules && npm install` confirms that the transform _is_ present and fixes the issue.
Moving to `prepublish` so we don't have to worry about `postinstall` issues anymore.

Remove postinstall

---

src/fragment.js
test/fragment.spec.js

`matchRoute(location.pathname)` can return null and if `fragment.js` were to evaluate `matchRoute(location.pathname).route` it would result in an unhandled exception.

ensure Fragment returns null if can't match any routes

---

src/store-enhancer.js
test/store-enhancer.spec.js

Adds some basic sanity checks for route configurations passed in to the store enhancer. Throws errors with some informational messages when the routes are empty or malformed (e.g. they don't all start with a slash).
/cc @baer @kriuz

Throw when routes are empty or malformed

---

src/link.js

Currently, adding an onClick handler to the Link causes strange behavior. This PR adds an explicit prop `onClick` that will always execute before routing code.

Add onClick handler

---

.travis.yml
README.md
package.json
src/provider.js
test/util/index.js

It's no longer required to manually `connect()` to get `<Link>` and `<Fragment>` rerenders working!
Resolves #38 
/cc @baer

Automatically connect() in RouterProvider to subscribe to state updates

---

src/fragment.js

wrapping the `children` object in a `<div>` in `Fragment` can have side effects with the CSS on the page. It doesn't seem like the `<div>` was doing anything, so this removes it.

Return unwrapped children from Fragment.

---

src/provider.js
src/store-enhancer.js
test/provider.spec.js
test/util/index.js

There's a use case for higher-level routing that attaches React component classes to the route results. Since components aren't serializable, Redux ignores any keys in the route object containing components, functions, or any other unserializable things.
This is a workaround, with the caveat that unserializable properties will only appear in `props.router.result` in the first child component of `<RouterProvider>`. I'd like a better solution before adding unserializable properties to `<RouterProvider>`'s `context`.
@kriuz can you pull this branch and `npm link` to make sure this works for you?
/cc @baer

Allow unserializable route properties (e.g. components) in routes

---

.flowconfig

(updated the `.flowconfig` to ignore it)

Fix flow choking on broken node module in CI

---

src/reducer.js
test/reducer.spec.js

This got lost when we stopped using the `current` key in the router state.

Fix undefined previous state

---

package.json
src/reducer.js

Right now, if a query parameter is changed but the pathname remains the same, the reducer does not persist the state.
I would add tests, but I've been unable to install some of the dev dependencies required for testing.

fix #90 - state unchanged after query change

---

src/link.js
test/link.spec.js
test/util/index.js

Resolves https://github.com/FormidableLabs/redux-little-router/issues/98
* `normalizeHref` now includes `location.search`  if it exists
* Adds tests that verify `href` is being rendered correctly
* Applies the `useQueries` enhancer to the `history`used in `fakeStore`. This is required to test that queries are being parsed correctly, and ideally the history instance in the testing environment should match the production instance as closely as possible.

Parse query in href

---

ADVANCED.md
README.md
demo/client/app.js
demo/server/index.js
src/browser-router.js
src/express-router.js
src/index.js
src/middleware.js
src/store-enhancer.js
test/browser-router.spec.js
test/express-router.spec.js
test/middleware.spec.js
test/store-enhancer.spec.js

This is the only way to allow consumer middleware to dispatch router actions.
/cc @divmain @baer

Bring back middleware :(

---

src/middleware.js
test/fragment.spec.js
test/provider.spec.js

When combining `redux-loop` with other middleware, [I've found it useful to put it after my middleware](https://blog.scottnonnenberg.com/better-async-redux-i18n-and-node-js-versions/#integrating-it-into-your-app). That way, all new actions generated by middleware will be processed by `redux-loop`. Then, `redux-loop` returns a promise from its overridden `dispatch()` which lets me know when the current action and any child `Effect` is done.
And so, any middleware which doesn't return the result of its `next()` call breaks that chain back up to the root `dispatch()` call.
This PR introduces that needed `return` statement in the router middleware.

Middleware returns, flowing downstream promises up to root dispatch

---

src/reducer-enhancer.js
test/store-enhancer.spec.js

This allows child reducers to depend on router state. Check out the diff on `router-enhancer.js`!
/cc @baer @divmain

Pass parent state to the enhanced router

---

src/browser-router.js
src/express-router.js
src/reducer-enhancer.js
src/store-enhancer.js
test/store-enhancer.spec.js

So I did  big dumb thing in `v11.1.0` by breaking typical usage of `combineReducers`. Since `combineReducers` filters out any keys it doesn't expect, router state never even gets to the store.
This PR makes passing router state optional, with the default case supporting `combineReducers`. I'll document this as a feature in ADVANCED.md soon.
/cc @baer @Aweary

Fix normal combineReducers usage by making router state passing optional

---

ADVANCED.md
src/hapi-router.js
src/index.js
test/express-router.spec.js
test/hapi-router.spec.js

This PR adds a `routerForHapi` that parallels the implementation of `routerForExpress`. The main difference is that Hapi doesn't currently support sub-routes with a `basename`/`baseUrl`, so the `routerForHapi` doesn't need to support `useBasename` from the history lib. The shape of a Hapi request is otherwise similar-enough to an Express request that there's nothing else needed to instantiate the history `location`.
I've confirmed this works in a currently-private project.

Hapi support with hapi-router

---

src/fragment.js
src/match-cache.js
src/store-enhancer.js
src/util/generate-id.js
test/fixtures/routes.js
test/fragment.spec.js
test/match-cache.spec.js

Implements greedy matching for `<RelativeFragment/>` by providing unique ids to fragments and tracking which route has been matched for each fragment, so sibling fragments know whether or not to render.
This would be a breaking change and require a major release as far as I can tell.
I'm still working on reviewing all the implications of this new matching system, but figured I'd open the PR for review 👍 
/cc @tptee 🎉

greedy route matching

---

src/browser-router.js
src/link.js
src/reducer.js
src/util/create-location.js
test/create-location.spec.js
test/link.spec.js
test/reducer.spec.js
test/util/index.js

Fixes regressions introduced in #125:
- `<Link>` didn't append `basename`s to `href`s
- `basename` disappeared from the router state after first user-initiated navigation
- Empty query objects appended an extraneous question mark to URLs
/cc @baer @divmain @scottnonnenberg

Fix multiple history v4 upgrade regressions

---

package.json

I have been seeing a peer dependency warning re. react-redux, and this PR bumps the version but maintains the older version (as established with the other peer dependencies). After a period of time—once it's fairly certain that 5.0 is in actuality a non-breaking release—the 4.0 option could be removed.
From the commit:
Though react-redux's [5.0.0 release is backwards compatible with 4.0.0])(https://github.com/reactjs/react-redux/releases/tag/v5.0.0), in the spirit of supporting multiple versions as with the react and react-dom dependency, this change allows either version to be used. 
This will silence the peer dependency warning.

Upgrades the peer dependency for react-redux to 5.0 (optionally 4)

---

src/components/fragment.js
test/components/fragment.spec.js
test/test-util/fixtures/routes.js

This addresses #114 by supporting nested relative index links `/`. I suppose it is a bit of a special case, but at the same time a fairly prevalent route pattern. So, here is my suggested fix. Thanks for all your work on this @tptee!

Add support for matching nested index (#114)

---

demo/client/demo.js
package.json
src/components/fragment.js
src/components/link.js
src/components/provider.js
test/components/provider.spec.js
yarn.lock

Resolves #156 
This PR fixes deprecation warnings about importing `PropTypes` from the latest React core package.
- Adds `prop-types` dependency
- Removes dependency on `React.PropTypes`
- Allows for full-support of React@15.5+
cc @tptee

Import PropTypes from 'prop-types'

---

src/components/fragment.js
test/components/fragment.spec.js
test/test-util/fixtures/routes.js

Supports exact matching every time a non root level fragment is matching on `forRoute="/"`. Added some more tests, but appreciate extra eyes on this. Addresses #154.

Fragments: support for nested / (slash) under parent / (slash)

---

src/components/link.js

Link now passes target to underlying <a> element. Fixes #164

Link passes target to underlying <a> element

---

src/components/link.js
src/reducer.js
test/components/link.spec.js
test/reducer.spec.js

Closes #172 and #132.
`persistQuery` merges in the new query into the old query instead of blowing the old one away. Also fixes a bug where the wrong href would display when persisting queries.

Merge old and new queries on persistQuery

---

demo/client/demo.css
demo/client/demo.js
src/components/fragment.js

Putting a `<Fragment forNoMatch />` as the last child of a nested route allows for 404 behavior.

Add 404 fragments

---

ADVANCED.md
src/actions.js
src/enhancer.js
src/index.js
src/install.js
src/reducer.js
src/types.js
test/actions.spec.js
test/enhancer.spec.js
test/install.spec.js
test/reducer.spec.js

Adds a `replaceRoutes` action creator that allows for changing the formerly static top-level routes. This'll allow for code splitting for people who still prefer top-level routing vs. dynamic `Fragment` matching.

Support replacing static routes

---

src/reducer.js
src/types.js
test/reducer.spec.js

This is the first half of the fix(es) that I outlined in https://github.com/FormidableLabs/redux-little-router/issues/211
* Implement `isNavigationActionWithPayload` 
* Define `actionsWithPayload` and `actions` instead of inlining the arrays in `isNavigationAction{WithPayload}`

Only enqueue payloads for navigation actions that have them

---

src/enhancer.js

Second part of the fix outlined in https://github.com/FormidableLabs/redux-little-router/issues/211#issuecomment-338770696
@tptee I couldn't figure out an easy way to test this. `enhancer.spec.js` is mocking `dispatch` for the store created by the `createStore` call in the test file, but it isn't mocking the store that's creating [inside the enhancer](https://github.com/FormidableLabs/redux-little-router/blob/master/src/enhancer.js#L33). To test this we'd probably want to somehow mock that internal store and assert that it's dispatching the correct payload for `POP` actions, but I can't figure out a clean way to do that 🤔  That `history.listen` callback depends on the dynamic `currentMatcher` variable in the parent scope so refactoring is kind of tricky.

Include parsed query in all history listener dispatches

---

src/enhancer.js
test/enhancer.spec.js

I had some trouble testing changes made to one of these callbacks in https://github.com/FormidableLabs/redux-little-router/pull/240, so here's a small refactor that makes them a bit more testable. This PR:
* Stops defining the callbacks as inline arrow functions and implements `createStoreSubscriber` and `createHistoryListener` instead. These functions accept some constant dependencies (like `store`) and return functions that can be called with the dynamic values like `currentMatcher`
* Adds tests for both of those new functions
I'm not sure it's the _best_ solution but it seems sufficient to me 🤷‍♂️

Refactor enhancer store subscriber and history listener

---

README.md

Fixes confusing omission of 'no' word in doc regarding <Fragment forNoMatch />

Add missing significant 'no' word in docs

---

README.md
demo/client/app.js
interfaces/history.js
src/actions.js
src/environment/browser-router.js
src/environment/express-router.js
src/environment/hapi-router.js
src/environment/hash-router.js
src/index.js
src/middleware.js
src/types.js
test/actions.spec.js
test/middleware.spec.js

Exposes `history`'s navigation confirmation/blocking API.

Add navigation confirmation/blocking API

---

README.md
demo/client/app.js
demo/client/demo.js
demo/server/index.js
package-lock.json
src/immutable/index.js
src/index.js

All `immutable` imports now must be separately imported. For example:
```
import { immutableRouterForBrowser, ImmutableLink } from 'redux-little-router/es/immutable';
import { combineReducers } from 'redux-immutable';
```

Move `immutable/*` re-exports to `immutable/index.js`

---

index.d.ts

Hey! I've got another bug in the TS typings that's waiting to be fixed. :)
`{}` does not represent a 'plain object' in TS. This leads to problems using `state.router.result.someProperty`, because TS asserts that `someProperty` doesn't exist, when in fact, it does. `any` is the right type to be used here.

Replace {} with any

---

index.d.ts

Pathname is optional in that you can do the following and it will work correctly:
```typescript
dispatch(push({ query: { something: "value" }));
```
I've updated the typings to reflect this and to be inline with the typings that were previously available at `@types/redux-little-router`

Make pathname optional in Typescript typings

---

index.d.ts

- Fix `History` interface to be compatible with the `@types/history` one
- `history` doesn't use Redux actions, action in this context is merely
a string (either `'POST'`, `'POP'` or `'REPLACE'`)
- Fix issue #288

Fix bug in `History` interface
